name: AWS Compliance Check

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual execution

jobs:
  compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install boto3

      - name: Fetch AWS Security Findings (Redacted)
        env:
          AWS_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python fetch_compliance.py

      - name: Verify Compliance Report
        run: |
          cat compliance-report.json || (echo "❌ Compliance report missing!" && exit 1)

      - name: Commit and Push Updated Report
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add compliance-report.json
          git commit -m "🔄 Updated compliance report (Redacted Vulnerabilities)"
          git push https://x-access-token:${GH_PAT}@github.com/ginosettecasi/aws-compliance-dashboard.git main
